### ISSUE TITLE
j1939 ValueError: list.remove(x): x not in list

### ISSUE THREAD

**Issue by ranaj007** [CSS-Electronics/dashboard-writer#10]
Running main.bat with tp_type in input.py set to "j1939" with multiple log files produced the following error:
![image](https://user-images.githubusercontent.com/108717666/217119734-297b5230-bbb4-42c6-a89f-280096a5e81b.png)

Not sure if this is due to the specific dbc file formatting as this has caused me a few other issues. Modifying line 342 in utils.py "res_id_list = res_id_list_full.remove(bam_pgn)" to "res_id_list = res_id_list_full.copy().remove(bam_pgn)" fixed the issue.

I have attached two example log files and a dbc file that cause the error.
[Example Files.zip](https://github.com/CSS-Electronics/canedge-influxdb-writer/files/10670511/Example.Files.zip)

**Comment by ranaj007** [comment]
I made a mistake in the above code, due to the way copy works with lists the code must be seperated into two lines,
from
"res_id_list = res_id_list_full.copy().remove(bam_pgn)"
to
"
res_id_list = res_id_list_full.copy()
res_id_list.remove(bam_pgn)
"

**Comment by MatinF** [comment]
I believe this should be resolved in the latest commit, if so I appreciate if you can close the issue. Thanks for reporting it!

**Comment by ranaj007** [comment]
Issue resolved in the latest commit.
