### ISSUE TITLE
Error when attempting to run using provided sample data

### ISSUE THREAD

**Issue by GalwayK** [CSS-Electronics/dashboard-writer#11]
When I attempt to run this program using the provided sample data, I get an error on line: 31.

I have made no changes to the program aside from entering my influxdb credentials. All requirements are installed. 

![Screenshot_20230210_015411](https://user-images.githubusercontent.com/97978733/218175379-8eaa5ab8-13b5-4549-bf52-fd86807a54e4.png)

**Comment by MatinF** [comment]
Thanks for reporting, there seems to be an issue with the update to `can_decoder==0.1.6` - you can try downgrading to `0.1.5`. A fix will be added next week.

**Comment by MatinF** [comment]
This should now be resolved with latest commit and `can_decoder==0.1.7`, thanks for reporting
