### ISSUE TITLE
Column Limit 

### ISSUE THREAD

**Issue by Huumour93** [CSS-Electronics/dashboard-writer#14]
I keep getting this error:

The batch item wasn't processed successfully because: (400)
Reason: Bad Request
HTTP response headers: HTTPHeaderDict({'Date': 'Tue, 09 May 2023 09:01:43 GMT', 'Content-Type': 'application/json', 'Content-Length': '216', 'Connection': 'keep-alive', 'trace-id': 'a5e2abe810cb6c3f', 'trace-sampled': 'false', 'Strict-Transport-Security': 'max-age=15724800; includeSubDomains', 'X-Influxdb-Request-ID': '3402a4e1bf06f25e3e0b3d6523c10cde', 'X-Influxdb-Build': 'Cloud'})
HTTP response body: {"code":"invalid","message":"dml handler error: service limit reached: couldn't create columns in table `E7DEAEE7`; table contains 199 existing columns, applying this write would result in 267 columns, limit is 200"}

I don't have the config file for influxdb to increase the limit for columns., please help.

**Comment by MatinF** [comment]
Have you double checked that you're running the correct Python 3.9 install and you're using a virtual environment as per the README with the correct dependencies?

**Comment by Huumour93** [comment]
yes I am

![python 3 9](https://github.com/CSS-Electronics/canedge-influxdb-writer/assets/130978010/1fd95cb3-d304-467f-9314-b8438707c672)

**Comment by MatinF** [comment]
can you try the following:

1) Re-download the repository
2) Run the install.bat and share the full console printout from this here
3) Run the main.bat and share the full console printout from this here

**Comment by Huumour93** [comment]
Redownloaded the repository

Ran install.bat
![image](https://github.com/CSS-Electronics/canedge-influxdb-writer/assets/130978010/c8509685-cf0c-48ea-9153-d723fed3cb95)
Ran main.bat
![image](https://github.com/CSS-Electronics/canedge-influxdb-writer/assets/130978010/5c41c082-ffbb-4c33-8c34-85c8e16c9efa)

**Comment by Huumour93** [comment]
![image](https://github.com/CSS-Electronics/canedge-influxdb-writer/assets/130978010/96d0885f-3a02-4ab6-b235-5c50a9307ecc)

**Comment by MatinF** [comment]
Hi again,

I suggest trying to send us a full zip incl. your DBC and inputs.py if possible via our contact form, then we can test if we can replicate the issue here.

**Comment by Huumour93** [comment]
Ok, I sent an email with the zip file.

**Comment by MatinF** [comment]
The issue seems to be that new InfluxDB accounts get setup based on their new IOx engine, while my account was setup on the older TSM engine. The new IOx engine has implemented a rule schema that restricts the total number of columns to 200. 

I'm checking if there's a simple way to remove that limit or to get setup with the TSM engine without having to self-host InfluxDB. But short term I recommend deleting your measurement and restricting your setup to write a max of 200 signals.

We'll update the README for now.
