### ISSUE TITLE
OSX/Darwin build

### ISSUE THREAD

**Issue by tfoldi** [CSS-Electronics/dashboard-writer#15]
hey, I would love to use these neat Grafana dashboards, but being an osx person I would prefer I could do some of the development on my Mac. I understand that `mdf-iter` is binary only, but any chances you can share darwin M1 builds?

**Comment by MatinF** [comment]
I'm afraid we're only supporting Windows/Linux - but you can deploy the writer on e.g. AWS Lambda in which case it does not have to run on your Mac
