### ISSUE TITLE
Error setting up Lambda

### ISSUE THREAD

**Issue by fmahannah** [CSS-Electronics/dashboard-writer#2]
When I try to parse the layer you provided I get this error:

arn:aws:lambda:us-east-2:319723967016:layer:css-dashboard-writer:4

**You are not authorized to perform: lambda:GetLayerVersion**

Without this I am not able to set up lambda to process logs from s3 and send to our influx db

Any help greatly appreciated!

**Comment by MatinF** [comment]
Thanks for reporting - can you please outline the exact steps you take to replicate this and share a screenshot? Then we'll be able to investigate.

**Comment by fmahannah** [comment]
I followed these instructions:

1. Create an [IAM execution](https://docs.aws.amazon.com/lambda/latest/dg/lambda-intro-execution-role.html) role with permissions: `AWSLambdaBasicExecutionRole` + `AmazonS3FullAccess`
2. Go to 'Services/Lambda', then select your S3 bucket region (upper right corner)
3. Add a new Lambda function with a name, a Python 3.7 environment and your execution role
4. Add a 'Trigger': Select S3, your test bucket, `All object create events` and suffix `.MF4`
5. Create a zip containing `lambda_handler.py`, `utils.py` and `inputs.py` (ensure your inputs are updated)
6. Upload the zip via the Lambda 'Actions' button and confirm that your code shows in the online code editor
7. Find the pre-built layer ARN for your AWS S3 region in the `lambda_layer_arns.csv` file
8. In the 'Designer' tap, click Layers/Add a layer/Specify an ARN and parse your ARN
When I try to parse the ARN from your CSV file for my region I get the error shown in the attached screenshot
![lamdaerror](https://user-images.githubusercontent.com/6472266/106366203-4ac14380-6308-11eb-9178-03ab53c93557.png)

**Comment by fmahannah** [comment]
It almost looks like the AWSLambdaBasicExecutionRole  does not give any actual access to the lambda service? It only lists write access to CLoudwatch logs?

**Comment by MatinF** [comment]
Hi again, did you also add the AmazonS3FullAccess permission to the user?

I tested just now and I'm unable to replicate this on my end. I tested with that ARN and using my user with AWSLambdaBasicExecutionRole + AmazonS3FullAccess as policies. It's not enough to only have the AWSLambdaBasicExecutionRole I believe.

**Comment by fmahannah** [comment]
Yes I followed the instructions exactly. See attached. I am logged in as the root user for the AWS account. 
Is it possible that the ARN is not giving me access to it?
![iamuserforlambda](https://user-images.githubusercontent.com/6472266/106369703-b19f2680-6321-11eb-8b8c-ad757daa083b.png)

**Comment by fmahannah** [comment]
Which user exacly has to have those permissions?  The user logged in to AWS?  I am logged in as the root user for the account
which should have full access to everything right?  I created the role in your instructions. How do I apply that role to
the logged in AWS user?

**Comment by fmahannah** [comment]
I gave those permissions to admin group, and to an IAM user account and I get the same error logged in as each.

Sorry

**Comment by MatinF** [comment]
Hi again,

I suggest you send us your AWS login credentials to our mail at contact@csselectronics.com. Please provide a link to this thread there and we'll try to login directly and see if we can get clarity on what is going on.

The mail will get to me so I'll be helping you out on it.

best,
Martin

**Comment by fmahannah** [comment]
I sent you the info you requested. Thanks!

**Comment by MatinF** [comment]
This should be solved now via the latest commit, with an updated set of ARN layers that are now correctly made public

**Comment by fmahannah** [comment]
Sorry to be a pest but now when I try to run the test I get this error

[ERROR] Runtime.ImportModuleError: Unable to import module 'lambda_function': No module named 'lambda_function' 

I have the three python files in the folder uploaded via zip file per instructions, so I am not sure if this might be an issue with the new layer?

I did not replace those files since github only showed changes to the csv with the arns in it

Thanks

**Comment by MatinF** [comment]
Hi you'll need to go to the `Runtime settingsInfo` and rename the lambda_function to match the filename of your main script, in your case lambda_handler. To minimize confusion, I've renamed the script to `lambda_function.py` as this should eliminate this confusion going forward. Let me know if it works then.

**Comment by fmahannah** [comment]
It seems that I must still be missing some files. I fixed the issue above and now the error is 

{
  "errorMessage": "Unable to import module 'lambda_handler': No module named 'utils_db'",
  "errorType": "Runtime.ImportModuleError"
}

**Comment by MatinF** [comment]
Hi again, you'll need in your folder also the `utils_db.py` file - can you try this?

**Comment by fmahannah** [comment]
Yes I tried that

**Comment by fmahannah** [comment]
Actually now I see a function error instead. Where should files needed for dbc conversion be placed? It is looking for our dbc file

[ERROR] FileNotFoundError: [Errno 2] No such file or directory: '/var/task/CSS-Electronics-OBD2-v1.4.dbc'

Thanks

**Comment by fmahannah** [comment]
For the test data you provided, what should be entered for the bucket info as now it is throwing an error that the bucket was not found?  Getting closer and I do appreciate your help

{
  "errorMessage": "The specified bucket does not exist",
  "errorType": "FileNotFoundError",
  "stackTrace": [
    "  File \"/var/task/lambda_function.py\", line 22, in lambda_handler\n    df_raw, device_id = proc.get_raw_data(log_file)\n",
    "  File \"/var/task/utils.py\", line 180, in get_raw_data\n    with self.fs.open(log_file, \"rb\") as handle:\n",
    "  File \"/opt/python/lib/python3.7/site-packages/fsspec/spec.py\", line 903, in open\n    **kwargs\n",
    "  File \"/opt/python/lib/python3.7/site-packages/s3fs/core.py\", line 378, in _open\n    autocommit=autocommit, requester_pays=requester_pays)\n",
    "  File \"/opt/python/lib/python3.7/site-packages/s3fs/core.py\", line 1097, in __init__\n    cache_type=cache_type)\n",
    "  File \"/opt/python/lib/python3.7/site-packages/fsspec/spec.py\", line 1224, in __init__\n    self.details = fs.info(path)\n",
    "  File \"/opt/python/lib/python3.7/site-packages/s3fs/core.py\", line 546, in info\n    return super(S3FileSystem, self).info(path)\n",
    "  File \"/opt/python/lib/python3.7/site-packages/fsspec/spec.py\", line 577, in info\n    out = self.ls(self._parent(path), detail=True, **kwargs)\n",
    "  File \"/opt/python/lib/python3.7/site-packages/s3fs/core.py\", line 619, in ls\n    files = self._ls(path, refresh=refresh)\n",
    "  File \"/opt/python/lib/python3.7/site-packages/s3fs/core.py\", line 487, in _ls\n    return self._lsdir(path, refresh)\n",
    "  File \"/opt/python/lib/python3.7/site-packages/s3fs/core.py\", line 409, in _lsdir\n    raise translate_boto_error(e)\n"
  ]
}

**Comment by fmahannah** [comment]
OK I have it closer now and when triggered it is giving me an error about my influx db permissions so I should be able to figure it out. Thanks again for all the help

**Comment by MatinF** [comment]
Hi again,

you'll need to place the relevant DBC file as part of the zip you create - we'll note this explicitly in the README.

When testing the data using the JSON test inputs as described, you'll need to use "valid" test data inputs if you want to get a successful response. Alternatively, you can "simply" test by uploading a log file via CANcloud once the function is setup and watching the logs.

**Comment by fmahannah** [comment]
I finally have everything working. tested by putting files into the s3 bucket and using cloudwatch to monitor the results. It correctly put the data into the influx db and the dashboard updated.

Thanks again!

**Comment by MatinF** [comment]
Great! Thanks for pointing out some of our README gaps and the layer issue! If you have ideas for further improvement, let us know.
