### ISSUE TITLE
Manage duplicate signal names 

### ISSUE THREAD

**Issue by FCam1** [CSS-Electronics/dashboard-writer#4]
Hi,

My .dbc is composed of several CAN Messages having the sames signals manes. So only 1 signal is sent to influxdb as explained [here](https://github.com/CSS-Electronics/dashboard-writer#multiple-channels).

I have tried to remove [these lines](https://github.com/CSS-Electronics/dashboard-writer/blob/8c5cb8d318372ce615fe95bc24277f6505c66faa/dashboard-writer/utils.py#L150) without effect : 
```
        #df_phys["datetime"] = df_phys.index
        #df_phys = df_phys.drop_duplicates(keep="first")
        #df_phys = df_phys.drop("datetime", 1)
```

1/ How to can I send every signal to influxdb ? 

2/ In a second step I would like to use [` add_signal_tags`](https://github.com/CSS-Electronics/dashboard-writer/blob/8c5cb8d318372ce615fe95bc24277f6505c66faa/dashboard-writer/utils_db.py#L52) in order to add tags and be able to recognize each signal. For that I need to be able to read signal's ID. How can I read each signal's ID ?  

Thanks

**Comment by MatinF** [comment]
Hi there,

You could modify the utils_db.py to enable the inclusion of CAN IDs in front of the signal names to make them unique ala ``can_id.signal_name`` assuming this combination suffices for global uniqueness.

To do so, you could modify this part:
https://github.com/CSS-Electronics/dashboard-writer/blob/master/dashboard-writer/utils_db.py#L76

By using a similar approach as used here:
https://github.com/CSS-Electronics/dashboard-writer/blob/master/dashboard-writer/utils.py#L76

Essentially, you would loop through both messages and signals to ensure you get a handle for the message ID, which you can then prefix to the signal name before sending the data to InfluxDB.

As for tags, a similar approach would provide you with the CAN IDs. I'm not sure, though, what the use case would be for the tags if you'd simply add the IDs (which could be added as above to the signal names directly).

Hope this clarifies, else please reopen.
