### ISSUE TITLE
No module named 's3fs'

### ISSUE THREAD

**Issue by Ludwig17** [CSS-Electronics/dashboard-writer#5]
Hey everyone, 

i have a small issue, i followed every step according to the aws s3 readme. After inserting the zip file with all its functions i get the errorMessage: 

{
  "errorMessage": "Unable to import module 'lambda_function.lambda_handler': No module named 's3fs'",
  "errorType": "Runtime.ImportModuleError",
  "requestId": "57bdff90-ffe6-403c-8a4e-9af062b0e003",
  "stackTrace": []
}
After looking up different solutions in stackoverflow they suggested to rename the handler to the created zipfile / lambda_function name. After trying these solutions it still wont work for me. Do you have any suggestions to solve this problem.

Greetings and have a nice week.
Wig

**Comment by MatinF** [comment]
Hi Wig,

did you install the ARN layer as per the guide using the latest ARN layer matching your region?

best,

**Comment by Ludwig17** [comment]
Hi Matin,

yes the ARN Layer was installed like Line Nr. 7 and 8 instructed. 
![grafik](https://user-images.githubusercontent.com/96470335/152113325-c6496f06-6859-4a6f-9878-5c3afe5ee861.png)

Greetings,
Wig

**Comment by MatinF** [comment]
Hi again,

I suggest reaching out via our contact form, we may need to be able to login to your account to review your setup to determine what may be the issue here.

best,
Martin
