### ISSUE TITLE
unknown error with main.py and utils_db.py

### ISSUE THREAD

**Issue by Raphael164** [CSS-Electronics/dashboard-writer#9]
Hello, I was wondering if there is anyone, who can help me with this issue.
The influxdb-writer is set to be execute by taskplanner in my Drive.
This is the message I get after it has been executed:

![Clipboard - 31  Januar 2023 14_23](https://user-images.githubusercontent.com/124141239/216002702-320db55e-c00b-4d8a-84f3-fd2ec8054845.png)

**Comment by MatinF** [comment]
I suggest ensuring that you're using the latest version of the repo and then test with our sample data first. Let me know if that works?

**Comment by MatinF** [comment]
Otherwise please share a replicable example via a zip file to us via our contact form

**Comment by Raphael164** [comment]
> I suggest ensuring that you're using the latest version of the repo and then test with our sample data first. Let me know if that works?

Hi, thanks for the reply. Is there a documentation on how to do tests with your sample data?

I am getting my data via S3. 
The Version i am using is from last week. Older versions seem to work perfectly fine

**Comment by MatinF** [comment]
The README should fully explain how to use the sample data. But I suggest sending a replicable example to us via the contact form, then we can review what may cause the issue.

**Comment by MatinF** [comment]
Closing this, let us know if still not resolved
